name: Triggering Events

on:
  push:
    branches:
      - "dev/*"

  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    # paths: 
    #   -

  workflow_dispatch: 

jobs:
  echo-event:
    runs-on: ubuntu-22.04
    steps:
      - name: Dump Event JSON 
        run: | 
           echo "Event: ${{ github.event_name }}"
            echo "Branch: ${{ github.ref }}"

          # Checking if this Works
